# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import letter.managers


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='letter',
            managers=[
                ('objects', letter.managers.LetterManager()),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='response',
            field=models.TextField(default=None, null=True),
        ),
    ]
